config/routes.rb
Rails.application.routes.draw do
  scope module: :web do
    root to: 'welcome#show'
    resource :session
    resources :registrations
    resources :events
    resource :calendar
  end

  namespace :web_api, defaults: {format: :json} do
    resources :event_objects
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  extend Enumerize

  belongs_to :user

  enumerize :repeat_period, in: { day: 1.day, week: 1.week, month: 1.month, year: 1.year }

  validates :user, presence: true
  validates :name, presence: true
  validates :date, presence: true
end

app/models/event_object.rb
class EventObject
  include ActiveModel::Model

  attr_accessor :id, :title, :start
end

app/models/guest.rb
class Guest
  def id
    'guest'
  end

  def guest?
    true
  end

  def to_s
    'Guest'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :events

  validates :email, presence: true, email: true, uniqueness: true

  def guest?
    false
  end

  def to_s
    full_name.presence || email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  after_action :verify_authorized
  after_action :verify_policy_scoped, only: :index

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/user_authentication.rb
module UserAuthentication
  extend ActiveSupport::Concern

  included do
    helper_method :current_user
    hide_action :current_user
  end

  class_methods do
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) || Guest.new
  end

  private

  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    @current_user = nil
    session.delete :user_id
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
  include UserAuthentication

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = t(:not_authorized)
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/web/calendars_controller.rb
class Web::CalendarsController < Web::ApplicationController
  def show
    authorize :calendar
  end
end

app/controllers/web/events_controller.rb
class Web::EventsController < Web::ApplicationController
  def new
    @event = current_user.events.build
    authorize @event
  end

  def create
    @event = current_user.events.build
    authorize @event
    if @event.update event_params
      redirect_to calendar_path
    else
      render :new
    end
  end

  def edit
    @event = Event.find params[:id]
    authorize @event
  end

  def update
    @event = Event.find params[:id]
    authorize @event
    if @event.update event_params
      redirect_to calendar_path
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find params[:id]
    authorize @event
    @event.destroy
    redirect_to calendar_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :date, :repeat_period)
  end
end

app/controllers/web/registrations_controller.rb
class Web::RegistrationsController < Web::ApplicationController
  def new
    authorize :registration
    @registration_user_type = RegistrationUserType.new
  end

  def create
    authorize :registration
    @registration_user_type = RegistrationUserType.create user_params

    if @registration_user_type.persisted?
      sign_in @registration_user_type
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:full_name, :email, :password, :password_confirmation)
  end
end

app/controllers/web/sessions_controller.rb
class Web::SessionsController < Web::ApplicationController
  def new
    authorize :session
    @session_form = SessionForm.new
  end

  def create
    authorize :session
    @session_form = SessionForm.new session_form_params

    if @session_form.valid?
      sign_in @session_form.user
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    authorize :session
    sign_out
    redirect_to root_path
  end

  private

  def session_form_params
    params.require(:session_form).permit(:email, :password)
  end
end

app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController
  def show
    authorize :welcome
  end
end

app/controllers/web_api/application_controller.rb
class WebApi::ApplicationController < ApplicationController
  include UserAuthentication
end

app/controllers/web_api/event_objects_controller.rb
class WebApi::EventObjectsController < WebApi::ApplicationController
  def index
    skip_policy_scope
    authorize :event_object

    event_objects = EventObjectsFilterQuery.perform(params[:start], params[:end])

    render json: event_objects
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/web/_flash.haml
- flash.each do |name, msg|
  .alert.alert-warning
    = msg

app/views/layouts/web/_navbar.haml
.navbar.navbar-default.navbar-static-top{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{data: {target: ".navbar-collapse", toggle: "collapse"}, type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Calendar', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if policy(:calendar).show?
          %li= link_to t('.calendar'), calendar_path
        - if policy(:event).new?
          %li= link_to t('.new_event'), new_event_path
      %ul.nav.navbar-nav.navbar-right
        %li.navbar-text= current_user
        - if policy(:session).new?
          %li= link_to t(:sign_in), new_session_path
        - if policy(:registration).new?
          %li= link_to t(:register), new_registration_path
        - if policy(:session).destroy?
          %li= link_to t(:sign_out), session_path, method: :delete

app/views/layouts/web/application.haml
!!!
%html
  %head
    %title Calendar
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1'}
    = csrf_meta_tags
  %body
    = render 'layouts/web/navbar'
    .container
      = render 'layouts/web/flash'
      = yield

app/views/web/calendars/show.haml
#calendar{data: {user_id: current_user.id}}

app/views/web/events/_form.haml
= simple_form_for event do |f|
  = f.input :name
  = f.input :date
  = f.input :repeat_period

  = f.button :submit

  - if event.persisted?
    = link_to t(:delete), @event, method: :delete, data: {confirm: t(:are_your_sure?)}, class: 'btn btn-danger pull-right'

app/views/web/events/edit.haml
= render 'form', event: @event

app/views/web/events/new.haml
= render 'form', event: @event

app/views/web/welcome/show.haml
= link_to 'Github repo', 'https://github.com/darkleaf/test-calendar'